require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AtividadesController do

  # This should return the minimal set of attributes required to create a valid
  # Atividade. As you add validations to Atividade, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AtividadesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all atividades as @atividades" do
      atividade = Atividade.create! valid_attributes
      get :index, {}, valid_session
      assigns(:atividades).should eq([atividade])
    end
  end

  describe "GET show" do
    it "assigns the requested atividade as @atividade" do
      atividade = Atividade.create! valid_attributes
      get :show, {:id => atividade.to_param}, valid_session
      assigns(:atividade).should eq(atividade)
    end
  end

  describe "GET new" do
    it "assigns a new atividade as @atividade" do
      get :new, {}, valid_session
      assigns(:atividade).should be_a_new(Atividade)
    end
  end

  describe "GET edit" do
    it "assigns the requested atividade as @atividade" do
      atividade = Atividade.create! valid_attributes
      get :edit, {:id => atividade.to_param}, valid_session
      assigns(:atividade).should eq(atividade)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Atividade" do
        expect {
          post :create, {:atividade => valid_attributes}, valid_session
        }.to change(Atividade, :count).by(1)
      end

      it "assigns a newly created atividade as @atividade" do
        post :create, {:atividade => valid_attributes}, valid_session
        assigns(:atividade).should be_a(Atividade)
        assigns(:atividade).should be_persisted
      end

      it "redirects to the created atividade" do
        post :create, {:atividade => valid_attributes}, valid_session
        response.should redirect_to(Atividade.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved atividade as @atividade" do
        # Trigger the behavior that occurs when invalid params are submitted
        Atividade.any_instance.stub(:save).and_return(false)
        post :create, {:atividade => { "title" => "invalid value" }}, valid_session
        assigns(:atividade).should be_a_new(Atividade)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Atividade.any_instance.stub(:save).and_return(false)
        post :create, {:atividade => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested atividade" do
        atividade = Atividade.create! valid_attributes
        # Assuming there are no other atividades in the database, this
        # specifies that the Atividade created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Atividade.any_instance.should_receive(:update_attributes).with({ "title" => "MyString" })
        put :update, {:id => atividade.to_param, :atividade => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested atividade as @atividade" do
        atividade = Atividade.create! valid_attributes
        put :update, {:id => atividade.to_param, :atividade => valid_attributes}, valid_session
        assigns(:atividade).should eq(atividade)
      end

      it "redirects to the atividade" do
        atividade = Atividade.create! valid_attributes
        put :update, {:id => atividade.to_param, :atividade => valid_attributes}, valid_session
        response.should redirect_to(atividade)
      end
    end

    describe "with invalid params" do
      it "assigns the atividade as @atividade" do
        atividade = Atividade.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Atividade.any_instance.stub(:save).and_return(false)
        put :update, {:id => atividade.to_param, :atividade => { "title" => "invalid value" }}, valid_session
        assigns(:atividade).should eq(atividade)
      end

      it "re-renders the 'edit' template" do
        atividade = Atividade.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Atividade.any_instance.stub(:save).and_return(false)
        put :update, {:id => atividade.to_param, :atividade => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested atividade" do
      atividade = Atividade.create! valid_attributes
      expect {
        delete :destroy, {:id => atividade.to_param}, valid_session
      }.to change(Atividade, :count).by(-1)
    end

    it "redirects to the atividades list" do
      atividade = Atividade.create! valid_attributes
      delete :destroy, {:id => atividade.to_param}, valid_session
      response.should redirect_to(atividades_url)
    end
  end

end
